<?php

declare(strict_types=1);

namespace Database\Seeders\Demo;

use App\Models\Club;
use App\Models\SportRegion;
use Illuminate\Database\Seeder;

class DemoClubsSeeder extends Seeder
{
    public function run(): void
    {
        $regions = SportRegion::all()->keyBy('long_name');

        foreach (self::getData() as $club) {
            $region = $regions->get($club['region']);

            if ($region === null) {
                continue;
            }

            Club::create([
                'abbr'        => $club['abbr'],
                'name'        => $club['name'],
                'region_id'   => $region->id,
                'oris_id'     => $club['oris_id'],
                'oris_number' => $club['oris_number'],
            ]);
        }
    }

    /** @return list<array{abbr: string, name: string, region: string, oris_id: string, oris_number: string}> */
    public static function getData(): array
    {
        return [
            ['abbr' => 'ABM', 'name' => 'KOB ALFA Brno', 'region' => 'Jihomoravská', 'oris_id' => '1', 'oris_number' => '1117'],
            ['abbr' => 'ABR', 'name' => 'A-team MTBO', 'region' => 'Hanácká', 'oris_id' => '2', 'oris_number' => '0920'],
            ['abbr' => 'ADA', 'name' => 'OOB Spartak Adamov', 'region' => 'Jihomoravská', 'oris_id' => '4', 'oris_number' => '0901'],
            ['abbr' => 'ALB', 'name' => 'OOB Albrechtice nad Orlicí', 'region' => 'Východočeská', 'oris_id' => '5', 'oris_number' => '0601'],
            ['abbr' => 'AOP', 'name' => 'Orientační Běh Opava', 'region' => 'MS kraj', 'oris_id' => '6', 'oris_number' => '0801'],
            ['abbr' => 'API', 'name' => 'OK Andante Písek', 'region' => 'Jihočeská', 'oris_id' => '8', 'oris_number' => '0420'],
            ['abbr' => 'ASU', 'name' => 'Magnus Orienteering', 'region' => 'Hanácká', 'oris_id' => '9', 'oris_number' => '0722'],
            ['abbr' => 'BBM', 'name' => 'BETA URSUS Rosice', 'region' => 'Jihomoravská', 'oris_id' => '11', 'oris_number' => '1114'],
            ['abbr' => 'BFM', 'name' => 'SKOB Frýdek-Místek', 'region' => 'MS kraj', 'oris_id' => '12', 'oris_number' => '0803'],
            ['abbr' => 'BKG', 'name' => 'Ó-Brněnské kolokvé gang', 'region' => 'Jihomoravská', 'oris_id' => '30478', 'oris_number' => '1122'],
            ['abbr' => 'BLI', 'name' => 'MTBO Bludný kořen', 'region' => 'Ještědská', 'oris_id' => '13', 'oris_number' => '0541'],
            ['abbr' => 'BOR', 'name' => 'OK Jiskra Nový Bor', 'region' => 'Ještědská', 'oris_id' => '14', 'oris_number' => '0501'],
            ['abbr' => 'BOV', 'name' => 'TJ Důlník Ostrava', 'region' => 'MS kraj', 'oris_id' => '15', 'oris_number' => '0804'],
            ['abbr' => 'BSO', 'name' => 'KOB Důlník Sokolov', 'region' => 'Západočeská', 'oris_id' => '18', 'oris_number' => '0301'],
            ['abbr' => 'BZP', 'name' => 'Báječné ženy v orientačním běhu', 'region' => 'Pražská', 'oris_id' => '1296', 'oris_number' => '0137'],
            ['abbr' => 'BZR', 'name' => 'Bratrstvo žďárských vrchů', 'region' => 'Vysočina', 'oris_id' => '20', 'oris_number' => '0723'],
            ['abbr' => 'CEL', 'name' => 'TJ Sokol Čelechodvice na Hané', 'region' => 'Hanácká', 'oris_id' => '21', 'oris_number' => '0902'],
            ['abbr' => 'CEP', 'name' => 'Čepící', 'region' => 'Pražská', 'oris_id' => '1596', 'oris_number' => '0138'],
            ['abbr' => 'CET', 'name' => 'TJ Loko Česká Třebová', 'region' => 'Východočeská', 'oris_id' => '22', 'oris_number' => '0602'],
            ['abbr' => 'CIP', 'name' => 'OOB Čimis', 'region' => 'Pražská', 'oris_id' => '22080', 'oris_number' => '0143'],
            ['abbr' => 'CPK', 'name' => 'TJ Sokol Červené Pečky', 'region' => 'Východočeská', 'oris_id' => '34493', 'oris_number' => '0640'],
            ['abbr' => 'CST', 'name' => 'OB Strakonice', 'region' => 'Jihočeská', 'oris_id' => '23', 'oris_number' => '0404'],
            ['abbr' => 'CTB', 'name' => 'SK OB Chotěboř', 'region' => 'Vysočina', 'oris_id' => '24', 'oris_number' => '0702'],
            ['abbr' => 'DCE', 'name' => 'KOB Dobřichovice', 'region' => 'Středočeská', 'oris_id' => '25', 'oris_number' => '0201'],
            ['abbr' => 'DCH', 'name' => 'Radioelektronika Cheb', 'region' => 'Západočeská', 'oris_id' => '1052', 'oris_number' => '0328'],
            ['abbr' => 'DKL', 'name' => 'KOB Kladno', 'region' => 'Středočeská', 'oris_id' => '26', 'oris_number' => '0202'],
            ['abbr' => 'DKP', 'name' => 'Oddíl OB Kotláře', 'region' => 'Pražská', 'oris_id' => '27', 'oris_number' => '0101'],
            ['abbr' => 'DLP', 'name' => 'OOB TJ Dukla Praha', 'region' => 'Pražská', 'oris_id' => '2244', 'oris_number' => '0139'],
            ['abbr' => 'DMS', 'name' => 'Dynamo Malá Skála', 'region' => 'Ještědská', 'oris_id' => '412', 'oris_number' => '0544'],
            ['abbr' => 'DOB', 'name' => 'KOB Dobruška', 'region' => 'Východočeská', 'oris_id' => '29', 'oris_number' => '0603'],
            ['abbr' => 'DOK', 'name' => 'OK Doksy', 'region' => 'Ještědská', 'oris_id' => '30', 'oris_number' => '0504'],
            ['abbr' => 'DOR', 'name' => 'OK Dobříš', 'region' => 'Středočeská', 'oris_id' => '31', 'oris_number' => '0216'],
            ['abbr' => 'DVP', 'name' => 'DVP ORIENTATION', 'region' => 'Pražská', 'oris_id' => '33', 'oris_number' => '0102'],
            ['abbr' => 'EKP', 'name' => 'VŠTJ Ekonom Praha', 'region' => 'Pražská', 'oris_id' => '34', 'oris_number' => '0103'],
            ['abbr' => 'FSP', 'name' => 'VSK ČVUT Fakulta Stavební Praha', 'region' => 'Pražská', 'oris_id' => '37', 'oris_number' => '0104'],
            ['abbr' => 'FYD', 'name' => 'Jizerský klub OB Frýdlant', 'region' => 'Ještědská', 'oris_id' => '38', 'oris_number' => '0506'],
            ['abbr' => 'GIG', 'name' => 'GIGANT Orienteering', 'region' => 'Valašská', 'oris_id' => '1512', 'oris_number' => '1021'],
            ['abbr' => 'HAV', 'name' => 'OB Havířov', 'region' => 'MS kraj', 'oris_id' => '39', 'oris_number' => '0806'],
            ['abbr' => 'HCE', 'name' => 'TJ Hostivice', 'region' => 'Středočeská', 'oris_id' => '40', 'oris_number' => '0203'],
            ['abbr' => 'HJL', 'name' => 'OB T.J. Sokol Horní Jelení', 'region' => 'Východočeská', 'oris_id' => '6691', 'oris_number' => '0638'],
            ['abbr' => 'HLV', 'name' => 'OB Holešov', 'region' => 'Valašská', 'oris_id' => '41', 'oris_number' => '1004'],
            ['abbr' => 'HOB', 'name' => 'SK OB Horní Benešov', 'region' => 'Hanácká', 'oris_id' => '42', 'oris_number' => '0807'],
            ['abbr' => 'HOR', 'name' => 'TJ Jiskra Hořice', 'region' => 'Východočeská', 'oris_id' => '43', 'oris_number' => '0605'],
            ['abbr' => 'CHA', 'name' => 'OK Chrastava', 'region' => 'Ještědská', 'oris_id' => '46', 'oris_number' => '0507'],
            ['abbr' => 'CHC', 'name' => 'K.O.B. Chochoň', 'region' => 'Východočeská', 'oris_id' => '47', 'oris_number' => '0607'],
            ['abbr' => 'CHT', 'name' => 'OOB SK Chrast', 'region' => 'Vysočina', 'oris_id' => '48', 'oris_number' => '0705'],
            ['abbr' => 'JEN', 'name' => 'OB Jenišovice', 'region' => 'Ještědská', 'oris_id' => '50', 'oris_number' => '0508'],
            ['abbr' => 'JES', 'name' => 'OK Rakovník', 'region' => 'Středočeská', 'oris_id' => '52', 'oris_number' => '0324'],
            ['abbr' => 'JHB', 'name' => 'TJ Jiskra Havlíčkův Brod', 'region' => 'Vysočina', 'oris_id' => '53', 'oris_number' => '0706'],
            ['abbr' => 'JIL', 'name' => 'OK Jilemnice', 'region' => 'Východočeská', 'oris_id' => '54', 'oris_number' => '0608'],
            ['abbr' => 'JJN', 'name' => 'Team Jizerky', 'region' => 'Ještědská', 'oris_id' => '8987', 'oris_number' => '0549'],
            ['abbr' => 'JLI', 'name' => 'OB Jizerky', 'region' => 'Ještědská', 'oris_id' => '1079', 'oris_number' => '0547'],
            ['abbr' => 'JPV', 'name' => 'Oddíl OS SK Prostějov', 'region' => 'Hanácká', 'oris_id' => '55', 'oris_number' => '0905'],
            ['abbr' => 'JZL', 'name' => 'TJ Jižní svahy Zlín', 'region' => 'Valašská', 'oris_id' => '56', 'oris_number' => '1005'],
            ['abbr' => 'KAM', 'name' => 'OK Kamenice', 'region' => 'Středočeská', 'oris_id' => '58', 'oris_number' => '0210'],
            ['abbr' => 'KAS', 'name' => 'KOB Kamenický Šenov', 'region' => 'Ještědská', 'oris_id' => '60', 'oris_number' => '0509'],
            ['abbr' => 'KBP', 'name' => 'KBP Praha', 'region' => 'Pražská', 'oris_id' => '61', 'oris_number' => '0106'],
            ['abbr' => 'KCK', 'name' => 'KOB Český Krumlov', 'region' => 'Jihočeská', 'oris_id' => '62', 'oris_number' => '0406'],
            ['abbr' => 'KDZ', 'name' => 'Klub dobré zprávy Lysá nad Labem', 'region' => 'Ještědská', 'oris_id' => '7290', 'oris_number' => '0548'],
            ['abbr' => 'KNC', 'name' => 'Sokol Kostelec n. Č. l.', 'region' => 'Středočeská', 'oris_id' => '63', 'oris_number' => '0204'],
            ['abbr' => 'KON', 'name' => 'KOB Konice', 'region' => 'Hanácká', 'oris_id' => '64', 'oris_number' => '0906'],
            ['abbr' => 'KOR', 'name' => 'OB DDM Kostelec nad Orlicí', 'region' => 'Východočeská', 'oris_id' => '320', 'oris_number' => '0633'],
            ['abbr' => 'KPY', 'name' => 'SOOB TJ Sokol Kralupy n.Vlt.', 'region' => 'Středočeská', 'oris_id' => '65', 'oris_number' => '0205'],
            ['abbr' => 'KRE', 'name' => 'OOB TJ Sokol Křemže', 'region' => 'Jihočeská', 'oris_id' => '66', 'oris_number' => '0407'],
            ['abbr' => 'KRL', 'name' => 'Kometa Kralovice', 'region' => 'Západočeská', 'oris_id' => '67', 'oris_number' => '0322'],
            ['abbr' => 'KRN', 'name' => 'KOS TJ Lokomotiva Krnov', 'region' => 'MS kraj', 'oris_id' => '68', 'oris_number' => '0907'],
            ['abbr' => 'KSH', 'name' => 'OB Kašperské Hory', 'region' => 'Západočeská', 'oris_id' => '70', 'oris_number' => '0303'],
            ['abbr' => 'KSU', 'name' => 'Klub vytrvalostních sportů Šumperk', 'region' => 'Hanácká', 'oris_id' => '71', 'oris_number' => '0908'],
            ['abbr' => 'KTA', 'name' => 'SK Kotnov Tábor', 'region' => 'Jihočeská', 'oris_id' => '72', 'oris_number' => '0408'],
            ['abbr' => 'KTI', 'name' => 'Klub orientačních sportů Tišnov', 'region' => 'Jihomoravská', 'oris_id' => '7473', 'oris_number' => '1121'],
            ['abbr' => 'KUB', 'name' => 'Koala Uherský Brod', 'region' => 'Valašská', 'oris_id' => '17488', 'oris_number' => '1022'],
            ['abbr' => 'KUL', 'name' => 'KOB Ústí nad Labem', 'region' => 'Ještědská', 'oris_id' => '73', 'oris_number' => '0542'],
            ['abbr' => 'KUN', 'name' => 'OB Kunvald', 'region' => 'Východočeská', 'oris_id' => '74', 'oris_number' => '0610'],
            ['abbr' => 'KUO', 'name' => 'KOB Ústí nad Orlicí', 'region' => 'Východočeská', 'oris_id' => '75', 'oris_number' => '0632'],
            ['abbr' => 'KVP', 'name' => 'Orientační oddíl SKV Praha', 'region' => 'Pražská', 'oris_id' => '76', 'oris_number' => '0136'],
            ['abbr' => 'KVS', 'name' => 'SKOB Kobra Vsetín', 'region' => 'Valašská', 'oris_id' => '77', 'oris_number' => '1006'],
            ['abbr' => 'KYL', 'name' => 'SK SP Kylešovice', 'region' => 'MS kraj', 'oris_id' => '78', 'oris_number' => '0809'],
            ['abbr' => 'LBE', 'name' => 'TJ Lokomotiva Beroun', 'region' => 'Středočeská', 'oris_id' => '79', 'oris_number' => '0209'],
            ['abbr' => 'LBM', 'name' => 'TJ Lokomotiva Ingstav Brno', 'region' => 'Jihomoravská', 'oris_id' => '80', 'oris_number' => '1103'],
            ['abbr' => 'LCE', 'name' => 'OOB TJ Slovan Luhačovice', 'region' => 'Valašská', 'oris_id' => '81', 'oris_number' => '1008'],
            ['abbr' => 'LCV', 'name' => 'TJ Lokomotiva Chomutov', 'region' => 'Západočeská', 'oris_id' => '82', 'oris_number' => '0304'],
            ['abbr' => 'LDC', 'name' => 'KOB Děčín', 'region' => 'Ještědská', 'oris_id' => '83', 'oris_number' => '0528'],
            ['abbr' => 'LIT', 'name' => 'KOB Litvínov', 'region' => 'Ještědská', 'oris_id' => '85', 'oris_number' => '0511'],
            ['abbr' => 'LIV', 'name' => 'Krušnohorský rogainingový klub Litvínov', 'region' => 'Západočeská', 'oris_id' => '86', 'oris_number' => '0326'],
            ['abbr' => 'LJN', 'name' => 'OOB TJ LIAZ Jablonec nad Nisou', 'region' => 'Ještědská', 'oris_id' => '87', 'oris_number' => '0512'],
            ['abbr' => 'LLI', 'name' => 'LOK-o Liberec', 'region' => 'Ještědská', 'oris_id' => '89', 'oris_number' => '0513'],
            ['abbr' => 'LME', 'name' => 'SK Los Mělník', 'region' => 'Středočeská', 'oris_id' => '219', 'oris_number' => '0217'],
            ['abbr' => 'LOU', 'name' => 'SK Moravan Louňovice', 'region' => 'Středočeská', 'oris_id' => '2113', 'oris_number' => '0221'],
            ['abbr' => 'LOV', 'name' => 'lepus.cz', 'region' => 'MS kraj', 'oris_id' => '91', 'oris_number' => '0825'],
            ['abbr' => 'LPM', 'name' => 'OK Lokomotiva Plzeň', 'region' => 'Západočeská', 'oris_id' => '92', 'oris_number' => '0306'],
            ['abbr' => 'LPU', 'name' => 'OK Lokomotiva Pardubice', 'region' => 'Východočeská', 'oris_id' => '93', 'oris_number' => '0612'],
            ['abbr' => 'LTP', 'name' => 'OOB TJ Lokomotiva Teplice', 'region' => 'Ještědská', 'oris_id' => '94', 'oris_number' => '0514'],
            ['abbr' => 'LTU', 'name' => 'OOB TJ Lokomotiva Trutnov', 'region' => 'Východočeská', 'oris_id' => '95', 'oris_number' => '0613'],
            ['abbr' => 'MAS', 'name' => 'OOB Ašobě', 'region' => 'Západočeská', 'oris_id' => '107', 'oris_number' => '0307'],
            ['abbr' => 'MBM', 'name' => 'O-mikron', 'region' => 'Jihomoravská', 'oris_id' => '108', 'oris_number' => '1119'],
            ['abbr' => 'MFP', 'name' => 'Matfyz Praha', 'region' => 'Pražská', 'oris_id' => '109', 'oris_number' => '0110'],
            ['abbr' => 'MIL', 'name' => 'Tesil Milevsko', 'region' => 'Jihočeská', 'oris_id' => '110', 'oris_number' => '0409'],
            ['abbr' => 'MKP', 'name' => 'SK Meteor Kačerov', 'region' => 'Pražská', 'oris_id' => '112', 'oris_number' => '0111'],
            ['abbr' => 'MLA', 'name' => 'MLOK Mariánské Lázně', 'region' => 'Západočeská', 'oris_id' => '113', 'oris_number' => '0308'],
            ['abbr' => 'MOS', 'name' => 'Most Orienteering', 'region' => 'Ještědská', 'oris_id' => '34959', 'oris_number' => '0551'],
            ['abbr' => 'MOV', 'name' => 'SKOB Ostrava', 'region' => 'MS kraj', 'oris_id' => '114', 'oris_number' => '0810'],
            ['abbr' => 'MTU', 'name' => 'MOF', 'region' => 'Východočeská', 'oris_id' => '6837', 'oris_number' => '0639'],
            ['abbr' => 'NEK', 'name' => 'Nejdek Orienteering', 'region' => 'Západočeská', 'oris_id' => '1882', 'oris_number' => '0329'],
            ['abbr' => 'NPA', 'name' => 'SK LOB Nová Paka', 'region' => 'Východočeská', 'oris_id' => '96', 'oris_number' => '0614'],
            ['abbr' => 'OAV', 'name' => 'Orienteering Adventure', 'region' => 'Východočeská', 'oris_id' => '2315', 'oris_number' => '0637'],
            ['abbr' => 'OBP', 'name' => 'Orbis Praha', 'region' => 'Pražská', 'oris_id' => '17307', 'oris_number' => '0142'],
            ['abbr' => 'OCB', 'name' => 'OC České Budějovice', 'region' => 'Jihočeská', 'oris_id' => '97', 'oris_number' => '0410'],
            ['abbr' => 'ODR', 'name' => 'SKOB Odry', 'region' => 'MS kraj', 'oris_id' => '98', 'oris_number' => '0811'],
            ['abbr' => 'ODV', 'name' => 'TJ Aero Odolena Voda', 'region' => 'Středočeská', 'oris_id' => '99', 'oris_number' => '0206'],
            ['abbr' => 'OKP', 'name' => 'SK OK 24 Praha', 'region' => 'Pražská', 'oris_id' => '100', 'oris_number' => '0112'],
            ['abbr' => 'ONO', 'name' => 'SKOB Ostrov', 'region' => 'Západočeská', 'oris_id' => '102', 'oris_number' => '0310'],
            ['abbr' => 'OOL', 'name' => 'SK Haná orienteering', 'region' => 'Hanácká', 'oris_id' => '103', 'oris_number' => '0924'],
            ['abbr' => 'OOP', 'name' => 'TJ Opava', 'region' => 'MS kraj', 'oris_id' => '104', 'oris_number' => '0812'],
            ['abbr' => 'OPI', 'name' => 'Orientační sporty Písek', 'region' => 'Jihočeská', 'oris_id' => '105', 'oris_number' => '0423'],
            ['abbr' => 'OPT', 'name' => 'Orientační sporty Prachatice', 'region' => 'Jihočeská', 'oris_id' => '13309', 'oris_number' => '0411'],
            ['abbr' => 'OSN', 'name' => 'SK Orientační sporty Nové Město na Moravě', 'region' => 'Vysočina', 'oris_id' => '106', 'oris_number' => '0710'],
            ['abbr' => 'OTK', 'name' => 'OOB TJ Jiskra Otrokovice', 'region' => 'Valašská', 'oris_id' => '118', 'oris_number' => '1010'],
            ['abbr' => 'PBM', 'name' => 'TJ Spartak 1. brněnská', 'region' => 'Jihomoravská', 'oris_id' => '119', 'oris_number' => '1104'],
            ['abbr' => 'PCB', 'name' => 'SKP České Budějovice', 'region' => 'Jihočeská', 'oris_id' => '120', 'oris_number' => '0412'],
            ['abbr' => 'PDY', 'name' => 'Běhej Poděbrady', 'region' => 'Středočeská', 'oris_id' => '1036', 'oris_number' => '0219'],
            ['abbr' => 'PEN', 'name' => 'OK RECO Sport', 'region' => 'Ještědská', 'oris_id' => '121', 'oris_number' => '0537'],
            ['abbr' => 'PGP', 'name' => 'SK Praga', 'region' => 'Pražská', 'oris_id' => '123', 'oris_number' => '0115'],
            ['abbr' => 'PHK', 'name' => 'OK 99 Hradec Králové', 'region' => 'Východočeská', 'oris_id' => '124', 'oris_number' => '0615'],
            ['abbr' => 'PLU', 'name' => 'TJ SOKOL Plumlov', 'region' => 'Hanácká', 'oris_id' => '125', 'oris_number' => '0910'],
            ['abbr' => 'PPU', 'name' => 'KOB Pardubice z.s.', 'region' => 'Východočeská', 'oris_id' => '126', 'oris_number' => '0616'],
            ['abbr' => 'PRK', 'name' => 'Ptačí rezervace Krupá', 'region' => 'Středočeská', 'oris_id' => '35725', 'oris_number' => '0224'],
            ['abbr' => 'PTE', 'name' => 'TJ Sokol Ptenění', 'region' => 'Hanácká', 'oris_id' => '127', 'oris_number' => '0912'],
            ['abbr' => 'PUL', 'name' => 'OOB USK Slavie Ústí n.L.', 'region' => 'Ještědská', 'oris_id' => '128', 'oris_number' => '0516'],
            ['abbr' => 'PVD', 'name' => 'OOB TJ Sokol Pražák', 'region' => 'Jihočeská', 'oris_id' => '129', 'oris_number' => '0413'],
            ['abbr' => 'PVP', 'name' => 'VSK Přírodní vědy Praha', 'region' => 'Pražská', 'oris_id' => '130', 'oris_number' => '0116'],
            ['abbr' => 'PZR', 'name' => 'UNITOP SKP Žďár nad Sázavou', 'region' => 'Vysočina', 'oris_id' => '131', 'oris_number' => '0711'],
            ['abbr' => 'RAZ', 'name' => 'Sokol Razová', 'region' => 'MS kraj', 'oris_id' => '34494', 'oris_number' => '0827'],
            ['abbr' => 'RBK', 'name' => 'SK Radioklub Blansko', 'region' => 'Jihomoravská', 'oris_id' => '133', 'oris_number' => '1105'],
            ['abbr' => 'RIC', 'name' => 'OB Říčany', 'region' => 'Středočeská', 'oris_id' => '672', 'oris_number' => '0218'],
            ['abbr' => 'ROU', 'name' => 'SKOB Roudnice nad Labem', 'region' => 'Středočeská', 'oris_id' => '134', 'oris_number' => '0207'],
            ['abbr' => 'ROZ', 'name' => 'OK Roztoky', 'region' => 'Středočeská', 'oris_id' => '136', 'oris_number' => '0212'],
            ['abbr' => 'RUM', 'name' => 'ZOOB Rumburk', 'region' => 'Ještědská', 'oris_id' => '509', 'oris_number' => '0546'],
            ['abbr' => 'RUZ', 'name' => 'TJ Růžená', 'region' => 'Vysočina', 'oris_id' => '137', 'oris_number' => '0712'],
            ['abbr' => 'SAD', 'name' => 'Sportovní akademie Dobříš', 'region' => 'Středočeská', 'oris_id' => '12478', 'oris_number' => '0223'],
            ['abbr' => 'SBK', 'name' => 'KOB START Blansko', 'region' => 'Jihomoravská', 'oris_id' => '138', 'oris_number' => '1106'],
            ['abbr' => 'SBR', 'name' => 'SKOB Bruntál', 'region' => 'Hanácká', 'oris_id' => '139', 'oris_number' => '0913'],
            ['abbr' => 'SCP', 'name' => 'OK Sparta Praha', 'region' => 'Pražská', 'oris_id' => '140', 'oris_number' => '0117'],
            ['abbr' => 'SFM', 'name' => 'O-RUNNAŘIT Beskydy', 'region' => 'MS kraj', 'oris_id' => '141', 'oris_number' => '0819'],
            ['abbr' => 'SHK', 'name' => 'OK Slavia Hradec Králové', 'region' => 'Východočeská', 'oris_id' => '142', 'oris_number' => '0617'],
            ['abbr' => 'SIT', 'name' => 'OK SILESIA', 'region' => 'MS kraj', 'oris_id' => '2648', 'oris_number' => '0826'],
            ['abbr' => 'SJC', 'name' => 'Sportcentrum Jičín', 'region' => 'Východočeská', 'oris_id' => '145', 'oris_number' => '0618'],
            ['abbr' => 'SJH', 'name' => 'SOS Jindřichův Hradec', 'region' => 'Vysočina', 'oris_id' => '146', 'oris_number' => '0713'],
            ['abbr' => 'SJI', 'name' => 'OK Jihlava', 'region' => 'Vysočina', 'oris_id' => '147', 'oris_number' => '0714'],
            ['abbr' => 'SJP', 'name' => 'KčT Slavoj Praha', 'region' => 'Pražská', 'oris_id' => '148', 'oris_number' => '0119'],
            ['abbr' => 'SKL', 'name' => 'SMS Team Kladno', 'region' => 'Středočeská', 'oris_id' => '149', 'oris_number' => '0213'],
            ['abbr' => 'SKM', 'name' => 'KOB Směr Kroměříž', 'region' => 'Valašská', 'oris_id' => '150', 'oris_number' => '1011'],
            ['abbr' => 'SKP', 'name' => 'AC Saké Kateřinky', 'region' => 'Pražská', 'oris_id' => '28559', 'oris_number' => '0144'],
            ['abbr' => 'SKT', 'name' => 'Orientační běh Klatovy', 'region' => 'Západočeská', 'oris_id' => '14070', 'oris_number' => '0331'],
            ['abbr' => 'SKV', 'name' => 'TJ Slovan Karlovy Vary', 'region' => 'Západočeská', 'oris_id' => '151', 'oris_number' => '0313'],
            ['abbr' => 'SLA', 'name' => 'SKOB Slaný', 'region' => 'Středočeská', 'oris_id' => '152', 'oris_number' => '0208'],
            ['abbr' => 'SLP', 'name' => 'OOB Slavia Praha', 'region' => 'Pražská', 'oris_id' => '153', 'oris_number' => '0120'],
            ['abbr' => 'SMB', 'name' => 'SKOB Mladá Boleslav', 'region' => 'Ještědská', 'oris_id' => '154', 'oris_number' => '0518'],
            ['abbr' => 'SMR', 'name' => 'SNS Smržovka', 'region' => 'Ještědská', 'oris_id' => '155', 'oris_number' => '0519'],
            ['abbr' => 'SNA', 'name' => 'TJ START Náchod', 'region' => 'Východočeská', 'oris_id' => '156', 'oris_number' => '0619'],
            ['abbr' => 'SOB', 'name' => 'SOBSA', 'region' => 'Pražská', 'oris_id' => '157', 'oris_number' => '0130'],
            ['abbr' => 'SOP', 'name' => 'OOB TJ Slezan Opava', 'region' => 'MS kraj', 'oris_id' => '158', 'oris_number' => '0814'],
            ['abbr' => 'SPC', 'name' => 'SPORTICUS team', 'region' => 'Středočeská', 'oris_id' => '1874', 'oris_number' => '0220'],
            ['abbr' => 'SPR', 'name' => 'SK SKI - SPORT Pradědí', 'region' => 'Hanácká', 'oris_id' => '2579', 'oris_number' => '0929'],
            ['abbr' => 'SRK', 'name' => 'SOOB Spartak Rychnov n.Kn.', 'region' => 'Východočeská', 'oris_id' => '159', 'oris_number' => '0620'],
            ['abbr' => 'SSP', 'name' => 'SK Stopa Praha', 'region' => 'Pražská', 'oris_id' => '160', 'oris_number' => '0121'],
            ['abbr' => 'SSU', 'name' => 'SK Severka Šumperk', 'region' => 'Hanácká', 'oris_id' => '161', 'oris_number' => '0914'],
            ['abbr' => 'STA', 'name' => 'OK Střelka', 'region' => 'Vysočina', 'oris_id' => '2185', 'oris_number' => '0725'],
            ['abbr' => 'STB', 'name' => 'TJ Stadion Nový Bor', 'region' => 'Ještědská', 'oris_id' => '162', 'oris_number' => '0520'],
            ['abbr' => 'STE', 'name' => 'SK SKI-OB Šternberk', 'region' => 'Hanácká', 'oris_id' => '163', 'oris_number' => '0915'],
            ['abbr' => 'STH', 'name' => 'SK Studenec', 'region' => 'Východočeská', 'oris_id' => '164', 'oris_number' => '0621'],
            ['abbr' => 'SVS', 'name' => 'Orientklub Vsetín', 'region' => 'Valašská', 'oris_id' => '166', 'oris_number' => '1012'],
            ['abbr' => 'SZP', 'name' => 'TJ Slovan Praha Zdravotník', 'region' => 'Pražská', 'oris_id' => '167', 'oris_number' => '0122'],
            ['abbr' => 'TAN', 'name' => 'TJ Tanvald', 'region' => 'Ještědská', 'oris_id' => '32537', 'oris_number' => '0550'],
            ['abbr' => 'TAP', 'name' => 'KOB Tretra Praha', 'region' => 'Pražská', 'oris_id' => '168', 'oris_number' => '0123'],
            ['abbr' => 'TBM', 'name' => 'KOS TJ Tesla Brno', 'region' => 'Jihomoravská', 'oris_id' => '169', 'oris_number' => '1108'],
            ['abbr' => 'TCB', 'name' => 'SK Technik České Budějovice', 'region' => 'Jihočeská', 'oris_id' => '170', 'oris_number' => '0421'],
            ['abbr' => 'TEP', 'name' => 'Tempo Praha', 'region' => 'Pražská', 'oris_id' => '172', 'oris_number' => '0124'],
            ['abbr' => 'TJH', 'name' => 'TJ Tolar Jindřichův Hradec', 'region' => 'Jihočeská', 'oris_id' => '173', 'oris_number' => '0415'],
            ['abbr' => 'TJN', 'name' => 'OOB TJ Tatran Jablonec n. N.', 'region' => 'Ještědská', 'oris_id' => '174', 'oris_number' => '0523'],
            ['abbr' => 'TJP', 'name' => 'TJ Sokol Troja', 'region' => 'Pražská', 'oris_id' => '175', 'oris_number' => '0125'],
            ['abbr' => 'TRC', 'name' => 'SKOB BETA Třinec', 'region' => 'MS kraj', 'oris_id' => '176', 'oris_number' => '0815'],
            ['abbr' => 'TRI', 'name' => 'TJ TŽ Třinec', 'region' => 'MS kraj', 'oris_id' => '177', 'oris_number' => '0816'],
            ['abbr' => 'TRT', 'name' => 'KOS Třešť', 'region' => 'Vysočina', 'oris_id' => '1883', 'oris_number' => '0715'],
            ['abbr' => 'TSU', 'name' => 'LKT 80 Šumperk', 'region' => 'Hanácká', 'oris_id' => '178', 'oris_number' => '0926'],
            ['abbr' => 'TTR', 'name' => 'OOB Třebíč', 'region' => 'Vysočina', 'oris_id' => '179', 'oris_number' => '0716'],
            ['abbr' => 'TUR', 'name' => 'OOB TJ Turnov', 'region' => 'Ještědská', 'oris_id' => '180', 'oris_number' => '0524'],
            ['abbr' => 'TUV', 'name' => 'SOK TJ Turnov', 'region' => 'Ještědská', 'oris_id' => '181', 'oris_number' => '0525'],
            ['abbr' => 'TVR', 'name' => 'TJ Sokol Vrbno pod Pradědem', 'region' => 'Hanácká', 'oris_id' => '2586', 'oris_number' => '0930'],
            ['abbr' => 'TYN', 'name' => 'OOB SK Týniště nad Orlicí', 'region' => 'Východočeská', 'oris_id' => '182', 'oris_number' => '0622'],
            ['abbr' => 'TZL', 'name' => 'SKOB Zlín', 'region' => 'Valašská', 'oris_id' => '183', 'oris_number' => '1013'],
            ['abbr' => 'UBM', 'name' => 'MENISKOS Brno', 'region' => 'Jihomoravská', 'oris_id' => '184', 'oris_number' => '1116'],
            ['abbr' => 'UOL', 'name' => 'SOB Olomouc', 'region' => 'Hanácká', 'oris_id' => '185', 'oris_number' => '0917'],
            ['abbr' => 'UVP', 'name' => 'Slovan Praha', 'region' => 'Pražská', 'oris_id' => '186', 'oris_number' => '0126'],
            ['abbr' => 'VAM', 'name' => 'OB Vamberk', 'region' => 'Východočeská', 'oris_id' => '187', 'oris_number' => '0623'],
            ['abbr' => 'VBA', 'name' => 'ŠK VAZKA Bratislava', 'region' => 'Pražská', 'oris_id' => '385', 'oris_number' => '3107'],
            ['abbr' => 'VBM', 'name' => 'VSK Mendelu Brno', 'region' => 'Jihomoravská', 'oris_id' => '188', 'oris_number' => '1111'],
            ['abbr' => 'VCB', 'name' => 'OB České Budějovice', 'region' => 'Jihočeská', 'oris_id' => '189', 'oris_number' => '0417'],
            ['abbr' => 'VEY', 'name' => 'YETTI Vejprty', 'region' => 'Západočeská', 'oris_id' => '190', 'oris_number' => '0325'],
            ['abbr' => 'VIC', 'name' => 'OB Vizovice', 'region' => 'Valašská', 'oris_id' => '191', 'oris_number' => '1020'],
            ['abbr' => 'VIM', 'name' => 'Ski klub Šumava Vimperk', 'region' => 'Jihočeská', 'oris_id' => '9298', 'oris_number' => '0425'],
            ['abbr' => 'VLI', 'name' => 'Slavia Liberec orienteering', 'region' => 'Ještědská', 'oris_id' => '194', 'oris_number' => '0526'],
            ['abbr' => 'VPM', 'name' => 'KOS Slavia Plzeň', 'region' => 'Západočeská', 'oris_id' => '196', 'oris_number' => '0317'],
            ['abbr' => 'VRB', 'name' => 'Sportovní klub ve Vrbně pod Pradědem', 'region' => 'MS kraj', 'oris_id' => '197', 'oris_number' => '0818'],
            ['abbr' => 'VRL', 'name' => 'OOS TJ Spartak Vrchlabí', 'region' => 'Východočeská', 'oris_id' => '198', 'oris_number' => '0624'],
            ['abbr' => 'VSP', 'name' => 'USK Praha', 'region' => 'Pražská', 'oris_id' => '199', 'oris_number' => '0127'],
            ['abbr' => 'VTA', 'name' => 'SC vebr-sport', 'region' => 'Jihočeská', 'oris_id' => '226', 'oris_number' => '0424'],
            ['abbr' => 'XBM', 'name' => 'ABND RACING TEAM', 'region' => 'Jihomoravská', 'oris_id' => '200', 'oris_number' => '1118'],
            ['abbr' => 'XHK', 'name' => 'MTBO Hradec Králové', 'region' => 'Východočeská', 'oris_id' => '686', 'oris_number' => '0634'],
            ['abbr' => 'XPU', 'name' => 'PARDUBICE BIKERS', 'region' => 'Východočeská', 'oris_id' => '201', 'oris_number' => '0627'],
            ['abbr' => 'ZAK', 'name' => 'OK Netopýr Zákupy', 'region' => 'Ještědská', 'oris_id' => '203', 'oris_number' => '0533'],
            ['abbr' => 'ZAM', 'name' => 'OB T.J. Sokol Žamberk', 'region' => 'Východočeská', 'oris_id' => '204', 'oris_number' => '0625'],
            ['abbr' => 'ZBM', 'name' => 'SK Brno Žabovřesky', 'region' => 'Jihomoravská', 'oris_id' => '205', 'oris_number' => '1113'],
            ['abbr' => 'ZBP', 'name' => 'OOB SK Zbraslav', 'region' => 'Pražská', 'oris_id' => '206', 'oris_number' => '0128'],
            ['abbr' => 'ZKP', 'name' => 'Ztracené kobylky', 'region' => 'Ještědská', 'oris_id' => '7288', 'oris_number' => '0140'],
            ['abbr' => 'ZLH', 'name' => 'OOB TJ Zlaté Hory', 'region' => 'Hanácká', 'oris_id' => '208', 'oris_number' => '0918'],
            ['abbr' => 'ZPV', 'name' => 'KOB ZPV Prostějov', 'region' => 'Hanácká', 'oris_id' => '209', 'oris_number' => '0919'],
            ['abbr' => 'ZUP', 'name' => 'MTBO ČZU Praha', 'region' => 'Pražská', 'oris_id' => '210', 'oris_number' => '0131'],
            ['abbr' => 'ZVO', 'name' => 'OB Zvole', 'region' => 'Středočeská', 'oris_id' => '211', 'oris_number' => '0215'],
        ];
    }
}
