<footer class="border-t border-terrain-line bg-terrain-nav text-terrain-on-nav">
    <div class="mx-auto grid max-w-terrain gap-8 px-4 py-10 sm:grid-cols-2 sm:px-6 lg:grid-cols-4">
        <div><x-ui.brand class="focus-visible:outline-terrain-accent!" /><p class="mt-4 text-sm opacity-80">Orientace nás posouvá dál.</p></div>
        <div><h2 class="mb-3 text-sm font-bold">Klub</h2><ul class="space-y-3 text-sm opacity-80"><li><a href="{{ url('/stranka/o-klubu') }}" class="hover:underline focus-visible:outline-terrain-accent!">Informace o klubu</a></li><li><a href="{{ url('/stranka/poradane-zavody') }}" class="hover:underline focus-visible:outline-terrain-accent!">Pořádané závody</a></li><li><a href="{{ url('/#kalendar') }}" class="hover:underline focus-visible:outline-terrain-accent!">Kalendář a mapa</a></li><li><a href="https://mapy.orientacnisporty.cz/cs/clubs/{{ strtolower((string) config('site-config.club.abbr')) }}" class="hover:underline focus-visible:outline-terrain-accent!">Naše mapy</a></li></ul></div>
        <div><h2 class="mb-3 text-sm font-bold">Orientační sporty</h2><ul class="space-y-3 text-sm opacity-80"><li><a href="http://zhusta.sky.cz/Jihomoravska_oblast" class="hover:underline focus-visible:outline-terrain-accent!">Jihomoravská oblast</a></li><li><a href="http://www.orientacnibeh.cz/" class="hover:underline focus-visible:outline-terrain-accent!">Orientační běh</a></li><li><a href="http://www.obpostupy.cz/" class="hover:underline focus-visible:outline-terrain-accent!">OB postupy</a></li><li><a href="{{ url('/stranka/odkazy') }}" class="hover:underline focus-visible:outline-terrain-accent!">Další odkazy</a></li></ul></div>
        <div><h2 class="mb-3 text-sm font-bold">DALIN</h2><ul class="space-y-3 text-sm opacity-80"><li><a href="https://docs.dalin.cz/napoveda/" class="hover:underline focus-visible:outline-terrain-accent!">Nápověda</a></li><li><a href="https://github.com/jzejda/dalin" class="hover:underline focus-visible:outline-terrain-accent!">Zdrojový kód</a></li><li><a href="https://discord.gg/b53nY3hQ3W" class="hover:underline focus-visible:outline-terrain-accent!">Discord</a></li><li><a href="https://webglobe.cz/?dealer=131151" class="hover:underline focus-visible:outline-terrain-accent!">Webglobe</a></li></ul></div>
    </div>
    <div class="mx-auto max-w-terrain border-t border-terrain-line px-4 py-5 text-xs opacity-80 sm:px-6">© {{ date('Y') }} {{ config('site-config.club.full_name') }} · Informační systém <a href="https://docs.dalin.cz" class="underline focus-visible:outline-terrain-accent!">DALIN</a></div>
</footer>
